# **Save and load**

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
%cd '/content/drive/My Drive/Colab Notebooks/db'

/content/drive/My Drive/Colab Notebooks/db


In [ ]:
!ls

In [ ]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.coef_

array([135.78767123])

In [ ]:
model.intercept_

180616.43835616432

In [ ]:
model.predict([[5000]])

array([859554.79452055])

## **Pickle**

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [ ]:
# Guardamos el archivo en formato pickle con el nombre de 'model_pickle'
import pickle
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

<h4 style='color:purple'>Load Saved Model</h4>

In [ ]:
# Abrimos el archivo 'model_pickle' y le damos el nombre de mp
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [ ]:
mp.coef_

array([135.78767123])

In [ ]:
mp.intercept_

180616.43835616432

In [ ]:
mp.predict([[5000]])

array([859554.79452055])

## **joblib**

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [ ]:
# Guardamos el archivo en formato joblib con el nombre de 'model_joblib'
from sklearn.externals import joblib
joblib.dump(model, 'model_joblib')

/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


['model_joblib']

<h4 style='color:purple'>Load Saved Model</h4>

In [ ]:
# Abrimos el archivo 'model_joblib' y le damos el nombre de mj
mj = joblib.load('model_joblib')

In [ ]:
mj.coef_

array([135.78767123])

In [ ]:
mj.intercept_

180616.43835616432

In [ ]:
mj.predict([[5000]])

array([859554.79452055])